data:
  population_max_size: 50
  number_of_llm_based_agents: 0

gtfs:
  recursion_search_depth: 0
  cache_enabled: false
  trip_query_range: [0]

agent:
  reschedule_activity_departure_time: false

workdir: "../experiments/baseline_50_0"
