data:
  population_max_size: 5
  number_of_llm_based_agents: 5

gtfs:
  cache_enabled: false
  mode: OTP
  max_trip_candidates: 5
  fixed_day: "20250305"

agent:
  reschedule_activity_departure_time: true
  long_term_memory_enabled: true
  quantify_time_window: false
  long_term_reflect_interval: 86400
  long_term_max_entries_query: 10
  llm_model: "openai/gpt-oss-120b"

workdir: "../experiments/gpt-oss-120b_02_fixed_date"
