data:
  population_max_size: 3
  number_of_llm_based_agents: 3

gtfs:
  cache_enabled: false
  mode: OTP
  max_trip_candidates: 3

agent:
  reschedule_activity_departure_time: true
  long_term_memory_enabled: true
  quantify_time_window: false
  long_term_reflect_interval: 86400
  long_term_max_entries_query: 10
  llm_model: "qwen/qwen3-32b"

workdir: "../experiments/qwen3_32B_3"
