data:
  population_max_size: 5
  number_of_llm_based_agents: 5

gtfs:
  cache_enabled: false
  mode: OTP

agent:
  reschedule_activity_departure_time: true
  long_term_memory_enabled: true
  quantify_time_window: false
  long_term_reflect_interval: 86400
  llm_model: "gpt-4"

workdir: "../experiments/gpt4_5"
