data:
  population_max_size: 50
  number_of_llm_based_agents: 50

gtfs:
  recursion_search_depth: 0
  cache_enabled: false
  trip_query_range: [-15, 0, 15]

agent:
  reschedule_activity_departure_time: false
  long_term_memory_enabled: false
  quantify_time_window: true
  llm_model: "mistral-7B-instruct-v0.3"

workdir: "../experiments/mistral7B_50_no_mem"
