data:
  population_max_size: 8
  number_of_llm_based_agents: 8

gtfs:
  cache_enabled: false
  mode: OTP
  max_trip_candidates: 5

agent:
  reschedule_activity_departure_time: true
  long_term_memory_enabled: true
  quantify_time_window: false
  long_term_reflect_interval: 86400
  long_term_max_entries_query: 10
  llm_model: "deepseek-r1-distill-llama-70b"

workdir: "../experiments/deepseek-r1-distill-llama-70b_01"
