data:
  population_max_size: 1
  number_of_llm_based_agents: 1

gtfs:
  cache_enabled: false
  mode: OTP

agent:
  reschedule_activity_departure_time: false
  long_term_memory_enabled: true
  quantify_time_window: false
  long_term_reflect_interval: 86400
  llm_model: "gpt-4"

workdir: "../experiments/baseline_1_0"
