data:
  population_max_size: 50
  number_of_llm_based_agents: 50

gtfs:
  recursion_search_depth: 0
  cache_enabled: false
  trip_query_range: [0, 15, -15]
  max_trip_candidates: 5

agent:
  reschedule_activity_departure_time: false
  long_term_memory_enabled: true
  quantify_time_window: true
  long_term_max_entries_query: 12
  long_term_reflect_interval: 43200  # 12 hours
  llm_model: "mistral-7B-instruct-v0.3"

workdir: "../experiments/mistral7B_50_mem_all"
